use_frameworks!

platform :ios, '8.0'

target 'HelloXXXPod_Example' do
  pod 'HelloXXXPod', :path => '../'

  target 'HelloXXXPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
